travis:
  secure:
    BINSTAR_TOKEN: XccdRLffFyGjr1ldQoXAg6YAKFruMMoOMt/MRlywoc4/hBy5tGEFf6k2G3p/GDJd+2sbd9iSUq7ZhaTFYB3PVPbfmauTnUPbpuXdTVSpAcfI0NSHObhJMhIkckhtqa14xwm1TfNa9jhphyoE3n9CTXNYrMs2S4Ovh4HS/ytjk7jw7AsZJTPnmta7YrTXY3JIb8T1rNATpHM+EUio46T0GURFb7ZOCs8yI6PZMxcqBLNmYmocHrxRql1xpyn2eUIIh/vMnO/OCLf8opFGfXkUhzomF77bqN10u1BWRz8MKRGiPLaYroaaPygyTOtVZkwJqUsIwBvwlXA5BQSL+QtOEPZPbFX24pC3fss1RyVzHftRzBFjw66vTOJLj5R4mDdA3PG9qxwGkE+lgdewo1d+zDzwLFH74peU79uwcuGvXCR0Fz2yQQ6NcVv+9Bfmn8uB2graGR5x7GLNSsUmmOFrQLVq36OBcHx1ruyIZF2fVToRHAaA4xEZB7+7z4i7nqgWyOD+aP3Y/KvW+d/xaxjXlz4hPy+oLu4+GN9rgLHnwYTsXYq3JttlUX5lgt0O3fQyqwSbo9iZUjZRR+A3ktl3P1t3b2GQv7B6lU3CZ1Samfsqsbw7D40fQfAOec0IKMLKMTXn8PuigiKlTtDl2Sefbzd1m+MZR9l59zygOiT4cnQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
